version: '3.7'
services:
  mariadb:
    image: mariadb:10.2.17
    volumes:
      - ./etc/dev/mysql:/var/lib/mysql:rw
      - ./etc/dev/mysql:/app
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel

  php:
    build:
      context: .
      dockerfile: etc/dev/PHP/Dockerfile-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./etc/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
